// IMPORTS
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { 
  useAccount, 
  useReadContract, 
  useWriteContract, 
  useBalance, 
  useWaitForTransactionReceipt
} from 'wagmi'
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { lotteryFactoryContractConfig } from '../contracts/lotteryFactoryContractConfig';
import { Button } from '@/components/ui/button';
import { 
  Card, 
  CardHeader, 
  CardTitle, 
  CardContent, 
} from '@/components/ui/card';
import { 
  Dialog, 
  DialogClose, 
  DialogContent, 
  DialogDescription, 
  DialogFooter,
  DialogHeader, 
  DialogTitle, 
  DialogTrigger 
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';
import { lotteryFunctionsContractConfig } from 'src/contracts/lotteryFunctionsContractConfig';

const AdminPanel: NextPage = () => {
    const { isConnected, address, chainId} = useAccount();
    const router = useRouter();

    const { data: owner} = useReadContract({
      ...lotteryFactoryContractConfig,
      functionName: 'owner',
      args: [],
    })

    const { data: lotteryCount} = useReadContract({
      ...lotteryFactoryContractConfig,
      functionName: 'getLotteryCount',
      args: [],
    })

    const {data: collectedFees,} = useBalance({
      address: lotteryFactoryContractConfig.address,
    });

    const {data: oracleAddress} = useReadContract({
      ...lotteryFactoryContractConfig,
      functionName: 'getOracle',
      args: [],
    });

    const {data: activeLottery} = useReadContract({
      ...lotteryFactoryContractConfig,
      functionName: 'getActiveLottery',
      args: [],
    });
    
    const [feePercentage, setFeePercentage] = useState(0);

    const [ticketPrice, setTicketPrice] = useState(0);

    const [ticketsCap, setTicketsCap] = useState(0);

    const [ticketsMaxOwners, setTicketsMaxOwners] = useState(0);

    const {data: lotteryHash,isPending: isCreating, writeContract: createLotteryWriteContract} = useWriteContract();
    const {data: oracleHash, isPending: isSetting, writeContract: setOracleWriteContract} = useWriteContract();
    const {data: lotteryEndHash, isPending: isEnding, writeContract: forceEndLotteryWriteContract} = useWriteContract();

    const { isLoading: lotteryCreationConfirming, isSuccess: lotteryCreated } =
    useWaitForTransactionReceipt({
      hash: lotteryHash,
    });
    const { isLoading: oracleSetConfirming, isSuccess: oracleSet } =
    useWaitForTransactionReceipt({
      hash: oracleHash,
    });
    const { isLoading: lotteryEndConfirming, isSuccess: lotteryEndConfirmed } =
    useWaitForTransactionReceipt({
      hash: lotteryEndHash,
    });
    
    function createLottery() {
      createLotteryWriteContract({
        ...lotteryFactoryContractConfig,
        functionName: 'createLottery',
        args: [feePercentage, ticketPrice, ticketsCap, ticketsMaxOwners],
      })
    }

    function forceEndLottery() {
      forceEndLotteryWriteContract({
        ...lotteryFunctionsContractConfig,
        functionName: 'forceEndLottery',
        args: [],
      })
    }

    function setOracle() {
      setOracleWriteContract({
        ...lotteryFactoryContractConfig,
        functionName: 'setOracle',
        args: [newOracleAddress],
      })
    }

    const [newOracleAddress, setNewOracleAddress] = useState('');

    function copyAddress(address: string) {
      navigator.clipboard.writeText(address);
      toast.success("Address copied to clipboard", {position: 'top-center'});
    }

    function addressEtherscanLink(address: string) {
      if (chainId === 1) {
        return `https://etherscan.io/address/${address}`
      }
      else if (chainId === 11155111) {
        return `https://sepolia.etherscan.io/address/${address}`
      }
    }

    useEffect(() => {
    if(address !== owner) {
      router.push('/');
    }

    if (!isConnected) {
        router.push('/');
    }
    }, [isConnected, router]);

    useEffect(() => {
      if(lotteryCreated) {
        toast("Lottery created", {position: 'top-center'});
      }

      if(oracleSet) {
        toast("Oracle set", {position: 'top-center'});
      }

      if(lotteryEndConfirmed) {
        toast("Lottery ended", {position: 'top-center'});
      }
    });

  return (
    <div className={styles.container}>
      <Head>
        <title>Blockchain Lottery</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href='/images/eth-icon.ico' type='image/x-icon' rel="icon" />
        </Head>

      <header className="flex justify-end">
        <div className='pt-2'>
          <ConnectButton />
        </div>
      </header>

      {/* <main className={styles.main}> */}
      <main className="flex flex-col">
      <div className='flex justify-start m-3'>
        <h1 className='text-5xl p-3'>
          Admin Panel {/* add etherscan link of contract */}
        </h1>
        <div className='pt-5'>
          <Button className='p-4' onClick={() => router.push('/lotteries')}>Go to lotteries</Button>
        </div>
      </div>

        <div className="grid grid-flow-rows-dense grid-cols-4 grid-rows-3">
          
          <Card className='m-4 flex flex-col'>
            <CardHeader>
              <CardTitle>Total fees accumulated: </CardTitle>
              <code>{Number(collectedFees?.value)} Wei | {Number(collectedFees?.value) / 1e18} Eth</code>
            </CardHeader>
            <CardContent>
              <Button className='w-full' disabled={Number(collectedFees?.value) == 0}>Withdraw</Button> 
              <Input type='number' step={1} placeholder='Amount in Wei'></Input>
            </CardContent>
          </Card>

          <Card className='m-4 flex flex-col'>
            <CardHeader>
              <CardTitle>Current oracle address: </CardTitle>
              <code className="hover:underline">
                {
                  oracleAddress == 0 ? 
                  "No oracle set" :  
                  String(oracleAddress).slice(0, 6) + "..." + String(oracleAddress).slice(36)
                } 
                <Button className={cn(oracleAddress == 0 ? "hidden" : "h-6 w-12 m-2")} onClick={() =>copyAddress(String(oracleAddress))}>copy</Button>
              </code>
            </CardHeader>
            <CardContent>
              <Button 
                className='w-full' 
                onClick={setOracle} 
                disabled={isSetting || oracleSetConfirming}>
                  {isSetting || oracleSetConfirming ? "Setting..." : "Set oracle"}
              </Button> 
              <Input 
                type='text' 
                onChange={(e) => setNewOracleAddress(e.target.value)}  
                placeholder='New oracle address'/>
            </CardContent>
          </Card>

          <Card className='m-4 flex flex-col'>
            <CardHeader>
              <CardTitle>Current lottery address & id: </CardTitle>
              <code className="hover:underline"> 
                {
                  activeLottery == 0 ? 
                  "No lottery deployed" : 
                  String(activeLottery).slice(0, 6) + "..." + String(activeLottery).slice(38)
                } 
                <Button className={cn(activeLottery == 0 ? "hidden" : "h-6 w-12 m-2")} onClick={() => copyAddress(String(activeLottery))}>copy</Button> 
              </code>
              <code> {activeLottery == 0 ? "" : "&" } </code>
              <code> {activeLottery == 0 ? "" : Number(lotteryCount) - 1} </code>
            </CardHeader>
            <CardContent>
              <Button 
                className='w-full' 
                disabled={activeLottery == 0 || isEnding || lotteryEndConfirming || oracleAddress == 0}
                onClick={forceEndLottery}>
                  {isEnding || lotteryEndConfirming ? "Ending..." : "End lottery"}
              </Button> 
            </CardContent>
          </Card>

          <Card className='m-4 flex flex-col'>
            <CardHeader>
              <CardTitle>Number of lotteries deployed / next lotteryId: </CardTitle>
              <code>{Number(lotteryCount)}</code>
            </CardHeader>
            <CardContent>
              <Dialog>
                <DialogTrigger asChild>
                  <Button 
                    className='w-full' 
                    disabled={activeLottery != 0 || isCreating || lotteryCreationConfirming || oracleAddress == 0}>
                      {isCreating || lotteryCreationConfirming ? "Creating..." : "Create lottery"}
                  </Button>
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>Lottery Config</DialogTitle>
                    <DialogDescription>
                      <Input 
                        className='m-1' 
                        type='number' 
                        step={1} 
                        min={1}
                        onChange={(e) => setFeePercentage(Number(e.target.value))} 
                        placeholder='Fee percentage (basis points / 1% = 100)'/>
                      <Input 
                        className='m-1' 
                        type='number' 
                        step={1}
                        min={1} 
                        onChange={(e) => setTicketPrice(Number(e.target.value))} 
                        placeholder='Ticket price in Wei'/>
                      <Input 
                        className='m-1' 
                        type='number' 
                        step={1}
                        min={1} 
                        onChange={(e) => setTicketsCap(Number(e.target.value))} 
                        placeholder='Max number of tickets'/>
                      <Input 
                        className='m-1' 
                        type='number' 
                        step={1}
                        min={1} 
                        onChange={(e) => setTicketsMaxOwners(Number(e.target.value))} 
                        placeholder='Max number of owners'/>
                    </DialogDescription>
                  </DialogHeader>
                  <DialogFooter>
                    <DialogClose asChild>
                      <Button  
                        onClick={createLottery}>Create lottery</Button>
                    </DialogClose>
                  </DialogFooter>
                </DialogContent>
              </Dialog>
            </CardContent>
          </Card>
          
        </div>
      </main>
    </div>
  );
};

export default AdminPanel;
