import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useAccount, useReadContract, useWriteContract, useBalance } from 'wagmi'
import { type UseReadContractReturnType } from 'wagmi'
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { lotteryFactoryContractConfig } from '../contracts/lotteryFactoryContractConfig';

const Lotteries: NextPage = () => {
    const { isConnected, address } = useAccount();
    const router = useRouter();

    // type loteryCount = UseReadContractReturnType<`0x${string}`, Error>

    useEffect(() => {
    if (!isConnected) {
        router.push('/');
    }
    }, [isConnected, router]);

    const { data: owner} = useReadContract({
      ...lotteryFactoryContractConfig,
      functionName: 'owner',
      args: [],
    })

    const { data: lotteryCount} = useReadContract({
      ...lotteryFactoryContractConfig,
      functionName: 'getLotteryCount',
      args: [],
    })

  return (
    <div className={styles.container}>
      <Head>
        <title>Blockchain Lottery</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Lotteries {/* add etherscan link of contract */}
        </h1>

        
        {/* <p>isConnected: {isConnected}</p> */}
        <button onClick={() => router.push('/admin-panel')}>Go to admin panel</button>
        <a>{String(owner) == String(address)}</a>    

        {/* <div className={styles.grid}>
          <a className={styles.card} href="https://rainbowkit.com">
            <h2>RainbowKit Documentation &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a className={styles.card} href="https://wagmi.sh">
            <h2>wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
          >
            <h2>RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a className={styles.card} href="https://nextjs.org/docs">
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/vercel/next.js/tree/canary/examples"
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            className={styles.card}
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <h5>
          Made by mksdznk. Full project code available on <a href="https://github.com/mksdznk/blockchain-lottery">GitHub</a>
        </h5>
        
      </footer>
    </div>
  );
};

export default Lotteries;
